### ISSUE TITLE
ITMS-90809: Deprecated API Usage for UIWebView

### ISSUE THREAD

**Issue by angelinec** [MOLPay/rms-mobile-xdk-cocoapods#5]
Hello,

I came across this warning issued by Apple after uploading my app to Appstore. It appears that UIWebView is being used in MOLPayXDK pod which has been deprecated. Previous version of my app was successfully uploaded without the warning until I use MOLPayXDK in my current app version.

Could you confirm this issue?
Any help is very much appreciated, thank you.

**Swift 5.0**
**Xcode 11**
**MOLPayXDK 3.27.0**

References:
<img width="520" alt="Screenshot 2019-10-11 at 12 16 12 PM" src="https://user-images.githubusercontent.com/9972417/66628796-79f30380-ec32-11e9-9ba0-5fa43b86b965.png">

<img width="695" alt="Screenshot 2019-10-11 at 12 22 48 PM" src="https://user-images.githubusercontent.com/9972417/66628808-824b3e80-ec32-11e9-8cc8-a3456d5ad2ee.png">

**Comment by clewlb** [comment]
Hi there,

Thanks for reaching out. We are aware of that UIWebView is going to deprecate soon, and we do have plan to upgrade our XDK from using UIWebView to WKWebView soon. For your information, iOS 13 will still be running the UIWebView and your app is completely now. You can subscribe to this repo should we roll-out the upgrade in the near future.

Thank you.

The XDK Team
