### ISSUE TITLE
Bitcode bundle could not be generated

### ISSUE THREAD

**Issue by fattynomnom** [MOLPay/rms-mobile-xdk-cocoapods#6]
Hi,

I'm getting this error while archiving my project:
bitcode bundle could not be generated because '/Users/madeleinechengmeitee/Documents/Xcode/TRP/Pods/MOLPayXDK/MOLPayXDK.framework/MOLPayXDK(MOLPayMainUI.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/madeleinechengmeitee/Documents/Xcode/TRP/Pods/MOLPayXDK/MOLPayXDK.framework/MOLPayXDK' for architecture arm64

How do you recommend I solve this error? Thanks!

**Comment by LeowWH** [comment]
@fattynomnom ,

Please try to use our latest .framework file to do the archive or you can try to use our Example project to do the archive as we cannot reproduce the issue using that thanks.

**Comment by fattynomnom** [comment]
So sorry, you were right, I wasn't using the latest framework. Thank you so much!
